# frozen_string_literal: true

require "erb"
require "fileutils"
require "yaml"

require "active_support"
require "active_support/core_ext/string/inflections"

module RBS
  class Template
    class Field
      attr_reader :name
      attr_reader :c_type

      def initialize(name:, c_type:)
        @name = name
        @c_type = c_type
      end

      def self.from_hash(hash)
        new(name: hash["name"], c_type: hash.fetch("c_type", "VALUE"))
      end

      # Returns a C expression that evaluates to the Ruby VALUE object for this field.
      def cached_ruby_value_expr
        case @c_type
        when "VALUE"
          @name
        when "rbs_node", "rbs_node_list", "rbs_location"
          "#{@name}->cached_ruby_value"
        else
          "#{@name}->base.cached_ruby_value"
        end
      end

      def parameter_decl
        if @c_type == "VALUE"
          "#{@c_type} #{@name}"
        else
          "#{@c_type}_t *#{@name}"
        end
      end

      def stored_field_decl
        if @c_type == "VALUE"
          "VALUE #{@name}"
        else
          "struct #{@c_type} *#{@name}"
        end
      end
    end

    class Type
      # The fully-qualified name of the auto-generated Ruby class for this type,
      # e.g. `RBS::AST::Declarations::TypeAlias`
      attr_reader :ruby_full_name #: String

      # The name of the name of the auto-generated Ruby class for this type,
      # e.g. `TypeAlias`
      attr_reader :ruby_class_name #: String

      # The base name of the auto-generated C struct for this type.
      # e.g. `rbs_ast_declarations_typealias`
      attr_reader :c_base_name #: String

      # The name of the typedef of the auto-generated C struct for this type,
      # e.g. `rbs_ast_declarations_typealias_t`
      attr_reader :c_type_name #: String

      # The name of the pre-existing C function which constructs new Ruby objects of this type.
      # e.g. `rbs_ast_declarations_typealias_new`
      attr_reader :c_function_name #: String

      # The name of the C constant which stores the Ruby VALUE pointing to the generated class.
      # e.g. `RBS_AST_Declarations_TypeAlias`
      attr_reader :c_constant_name #: String

      # The name of the C constant in which the `c_constant_name` is nested.
      # e.g. `RBS_AST_Declarations`
      attr_reader :c_parent_constant_name #: String

      attr_reader :c_struct_name #: String
      attr_reader :c_type_enum_name #: String

      attr_reader :fields #: Array[RBS::Template::Field]

      def initialize(yaml)
        @ruby_full_name = yaml["name"]
        @ruby_class_name = @ruby_full_name.demodulize
        @c_function_name = if @ruby_full_name =~ /^RBS::Types/
          name = @ruby_full_name.gsub("::", "_").underscore
          name.gsub("_types_", "_")
        else
          name = @ruby_full_name.gsub("::", "_").underscore
          name.gsub("_declarations_", "_decl_")
        end
        @c_constant_name = @ruby_full_name.gsub("::", "_")
        @c_parent_constant_name = @ruby_full_name.split("::")[0..-2].join("::").gsub("::", "_")
        @c_base_name = @c_constant_name.downcase
        @c_type_name = @c_base_name + "_t"

        @c_struct_name = "#{@c_base_name}_t"
        @c_type_enum_name = @c_base_name.upcase

        @fields = yaml.fetch("fields", []).map { |field| Field.from_hash(field) }.freeze

        @expose_to_ruby = yaml.fetch("expose_to_ruby", true)

        @builds_ruby_object_internally = yaml.fetch("builds_ruby_object_internally", true)
      end

      # The name of the C function which constructs new instances of this C structure.
      # e.g. `rbs_ast_declarations_typealias_new`
      def c_constructor_function_name #: String
        "#{@c_base_name}_new"
      end

      # Every templated type will have a C struct created for it.
      # If this is true, then we will also create a Ruby class for it, otherwise we'll skip that.
      def expose_to_ruby?
        @expose_to_ruby
      end

      # When true, this object is expected to build its own Ruby VALUE object inside its `*_new()` function.
      # When false, the `*_new()` function will take a Ruby VALUE as its first argument.
      def builds_ruby_object_internally?
        @builds_ruby_object_internally
      end

      def constructor_parameters
        if builds_ruby_object_internally?
          @fields
        else
          [Field.new(name: "ruby_value", c_type: "VALUE")] + @fields
        end
      end
    end

    class << self
      def render(out_file)
        filepath = "templates/#{out_file}.erb"
        template = File.expand_path("../#{filepath}", __dir__)

        erb = read_template(template)
        extension = File.extname(filepath.gsub(".erb", ""))

        heading = <<~HEADING
          /*----------------------------------------------------------------------------*/
          /* This file is generated by the templates/template.rb script and should not  */
          /* be modified manually.                                                      */
          /* To change the template see                                                 */
          /* #{filepath + " " * (74 - filepath.size) } */
          /*----------------------------------------------------------------------------*/
        HEADING

        write_to = File.expand_path("../#{out_file}", __dir__)
        contents = heading + "\n" + erb.result_with_hash(locals)

        if (extension == ".c" || extension == ".h") && !contents.ascii_only?
          # Enforce that we only have ASCII characters here. This is necessary
          # for non-UTF-8 locales that only allow ASCII characters in C source
          # files.
          contents.each_line.with_index(1) do |line, line_number|
            raise "Non-ASCII character on line #{line_number} of #{write_to}" unless line.ascii_only?
          end
        end

        FileUtils.mkdir_p(File.dirname(write_to))
        File.write(write_to, contents)
      end

      private

      def read_template(filepath)
        template = File.read(filepath, encoding: Encoding::UTF_8)
        erb = erb(template)
        erb.filename = filepath
        erb
      end

      def erb(template)
        ERB.new(template, trim_mode: "-")
      end

      def locals
        config = YAML.load_file(File.expand_path("../config.yml", __dir__))
        {
          nodes: config.fetch("nodes").map { |node| Type.new(node) }.sort_by(&:ruby_full_name),
        }
      end
    end
  end
end

unless ARGV.size == 1
  $stderr.puts "Usage: ruby template.rb <out_file>"
  exit 1
end

out_file = ARGV.first
RBS::Template.render(out_file)
