/*----------------------------------------------------------------------------*/
/* This file is generated by the templates/template.rb script and should not  */
/* be modified manually.                                                      */
/* To change the template see                                                 */
/* templates/ext/rbs_extension/ast_translation.c.erb                          */
/*----------------------------------------------------------------------------*/

#include "ast_translation.h"
#include "rbs_extension.h"

#ifdef RB_PASS_KEYWORDS
// Ruby 2.7 or later
#define CLASS_NEW_INSTANCE(klass, argc, argv)\
        rb_class_new_instance_kw(argc, argv, klass, RB_PASS_KEYWORDS)
#else
// Ruby 2.6
#define CLASS_NEW_INSTANCE(receiver, argc, argv)\
        rb_class_new_instance(argc, argv, receiver)
#endif

const char* get_class_name(VALUE o) {
    VALUE klass = rb_class_of(o);      // Get the class of the object
    VALUE klass_name = rb_class_name(klass);  // Get the name of the class
    const char* name = StringValueCStr(klass_name);  // Convert to C string
    return name;
}

VALUE rbs_struct_to_ruby_value(rbs_node_t *instance) {
    switch (instance->type) {
        case RBS_AST_ANNOTATION: {
            rbs_ast_annotation_t *node = (rbs_ast_annotation_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("string")), node->string);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Annotation,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->string);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_COMMENT: {
            rbs_ast_comment_t *node = (rbs_ast_comment_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("string")), node->string);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Comment,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->string);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_CLASS: {
            rbs_ast_declarations_class_t *node = (rbs_ast_declarations_class_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type_params")), node->type_params);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("super_class")), node->super_class);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("members")), node->members);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_Class,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type_params);
            rb_gc_unregister_address(&node->super_class);
            rb_gc_unregister_address(&node->members);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_CLASS_SUPER: {
            rbs_ast_declarations_class_super_t *node = (rbs_ast_declarations_class_super_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("args")), node->args);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_Class_Super,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->args);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_CLASS_ALIAS: {
            rbs_ast_declarations_class_alias_t *node = (rbs_ast_declarations_class_alias_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("new_name")), node->new_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("old_name")), node->old_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_ClassAlias,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->new_name);
            rb_gc_unregister_address(&node->old_name);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_CONSTANT: {
            rbs_ast_declarations_constant_t *node = (rbs_ast_declarations_constant_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_Constant,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_GLOBAL: {
            rbs_ast_declarations_global_t *node = (rbs_ast_declarations_global_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_Global,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_INTERFACE: {
            rbs_ast_declarations_interface_t *node = (rbs_ast_declarations_interface_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type_params")), node->type_params);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("members")), node->members);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_Interface,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type_params);
            rb_gc_unregister_address(&node->members);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_MODULE: {
            rbs_ast_declarations_module_t *node = (rbs_ast_declarations_module_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type_params")), node->type_params);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("self_types")), node->self_types);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("members")), node->members);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_Module,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type_params);
            rb_gc_unregister_address(&node->self_types);
            rb_gc_unregister_address(&node->members);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_MODULE_SELF: {
            rbs_ast_declarations_module_self_t *node = (rbs_ast_declarations_module_self_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("args")), node->args);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_Module_Self,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->args);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_MODULE_ALIAS: {
            rbs_ast_declarations_module_alias_t *node = (rbs_ast_declarations_module_alias_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("new_name")), node->new_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("old_name")), node->old_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_ModuleAlias,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->new_name);
            rb_gc_unregister_address(&node->old_name);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_DECLARATIONS_TYPE_ALIAS: {
            rbs_ast_declarations_type_alias_t *node = (rbs_ast_declarations_type_alias_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type_params")), node->type_params);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Declarations_TypeAlias,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type_params);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_DIRECTIVES_USE: {
            rbs_ast_directives_use_t *node = (rbs_ast_directives_use_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("clauses")), node->clauses);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Directives_Use,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->clauses);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_DIRECTIVES_USE_SINGLE_CLAUSE: {
            rbs_ast_directives_use_single_clause_t *node = (rbs_ast_directives_use_single_clause_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type_name")), node->type_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("new_name")), node->new_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Directives_Use_SingleClause,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->type_name);
            rb_gc_unregister_address(&node->new_name);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_DIRECTIVES_USE_WILDCARD_CLAUSE: {
            rbs_ast_directives_use_wildcard_clause_t *node = (rbs_ast_directives_use_wildcard_clause_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("namespace")), node->namespace);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Directives_Use_WildcardClause,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->namespace);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_ALIAS: {
            rbs_ast_members_alias_t *node = (rbs_ast_members_alias_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("new_name")), node->new_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("old_name")), node->old_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("kind")), node->kind);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_Alias,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->new_name);
            rb_gc_unregister_address(&node->old_name);
            rb_gc_unregister_address(&node->kind);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_ATTR_ACCESSOR: {
            rbs_ast_members_attr_accessor_t *node = (rbs_ast_members_attr_accessor_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("ivar_name")), node->ivar_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("kind")), node->kind);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("visibility")), node->visibility);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_AttrAccessor,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->ivar_name);
            rb_gc_unregister_address(&node->kind);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);
            rb_gc_unregister_address(&node->visibility);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_ATTR_READER: {
            rbs_ast_members_attr_reader_t *node = (rbs_ast_members_attr_reader_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("ivar_name")), node->ivar_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("kind")), node->kind);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("visibility")), node->visibility);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_AttrReader,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->ivar_name);
            rb_gc_unregister_address(&node->kind);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);
            rb_gc_unregister_address(&node->visibility);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_ATTR_WRITER: {
            rbs_ast_members_attr_writer_t *node = (rbs_ast_members_attr_writer_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("ivar_name")), node->ivar_name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("kind")), node->kind);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("visibility")), node->visibility);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_AttrWriter,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->ivar_name);
            rb_gc_unregister_address(&node->kind);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);
            rb_gc_unregister_address(&node->visibility);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_CLASS_INSTANCE_VARIABLE: {
            rbs_ast_members_class_instance_variable_t *node = (rbs_ast_members_class_instance_variable_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_ClassInstanceVariable,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_CLASS_VARIABLE: {
            rbs_ast_members_class_variable_t *node = (rbs_ast_members_class_variable_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_ClassVariable,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_EXTEND: {
            rbs_ast_members_extend_t *node = (rbs_ast_members_extend_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("args")), node->args);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_Extend,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->args);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_INCLUDE: {
            rbs_ast_members_include_t *node = (rbs_ast_members_include_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("args")), node->args);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_Include,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->args);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_INSTANCE_VARIABLE: {
            rbs_ast_members_instance_variable_t *node = (rbs_ast_members_instance_variable_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_InstanceVariable,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_METHOD_DEFINITION: {
            rbs_ast_members_method_definition_t *node = (rbs_ast_members_method_definition_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("kind")), node->kind);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("overloads")), node->overloads);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("overloading")), node->overloading);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("visibility")), node->visibility);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_MethodDefinition,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->kind);
            rb_gc_unregister_address(&node->overloads);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);
            rb_gc_unregister_address(&node->overloading);
            rb_gc_unregister_address(&node->visibility);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_METHOD_DEFINITION_OVERLOAD: {
            rbs_ast_members_method_definition_overload_t *node = (rbs_ast_members_method_definition_overload_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("method_type")), node->method_type);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_MethodDefinition_Overload,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->method_type);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_PREPEND: {
            rbs_ast_members_prepend_t *node = (rbs_ast_members_prepend_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("args")), node->args);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("annotations")), node->annotations);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("comment")), node->comment);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_Prepend,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->args);
            rb_gc_unregister_address(&node->annotations);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->comment);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_PRIVATE: {
            rbs_ast_members_private_t *node = (rbs_ast_members_private_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_Private,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_MEMBERS_PUBLIC: {
            rbs_ast_members_public_t *node = (rbs_ast_members_public_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_Members_Public,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_AST_TYPE_PARAM: {
            rbs_ast_type_param_t *node = (rbs_ast_type_param_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("variance")), node->variance);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("upper_bound")), node->upper_bound);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("default_type")), node->default_type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_AST_TypeParam,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->variance);
            rb_gc_unregister_address(&node->upper_bound);
            rb_gc_unregister_address(&node->default_type);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_METHOD_TYPE: {
            rbs_method_type_t *node = (rbs_method_type_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type_params")), node->type_params);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("block")), node->block);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_MethodType,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->type_params);
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->block);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_NAMESPACE: {
            rbs_namespace_t *node = (rbs_namespace_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("path")), node->path);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("absolute")), node->absolute);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Namespace,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->path);
            rb_gc_unregister_address(&node->absolute);

            free(instance);

            return obj;
        }
        case RBS_TYPE_NAME: {
            rbs_type_name_t *node = (rbs_type_name_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("namespace")), node->namespace);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_TypeName,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->namespace);
            rb_gc_unregister_address(&node->name);

            free(instance);

            return obj;
        }
        case RBS_TYPES_ALIAS: {
            rbs_types_alias_t *node = (rbs_types_alias_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("args")), node->args);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Alias,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->args);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_ANY: {
            rbs_types_bases_any_t *node = (rbs_types_bases_any_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("todo")), node->todo);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Any,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->todo);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_BOOL: {
            rbs_types_bases_bool_t *node = (rbs_types_bases_bool_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Bool,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_BOTTOM: {
            rbs_types_bases_bottom_t *node = (rbs_types_bases_bottom_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Bottom,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_CLASS: {
            rbs_types_bases_class_t *node = (rbs_types_bases_class_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Class,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_INSTANCE: {
            rbs_types_bases_instance_t *node = (rbs_types_bases_instance_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Instance,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_NIL: {
            rbs_types_bases_nil_t *node = (rbs_types_bases_nil_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Nil,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_SELF: {
            rbs_types_bases_self_t *node = (rbs_types_bases_self_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Self,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_TOP: {
            rbs_types_bases_top_t *node = (rbs_types_bases_top_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Top,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BASES_VOID: {
            rbs_types_bases_void_t *node = (rbs_types_bases_void_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Bases_Void,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_BLOCK: {
            rbs_types_block_t *node = (rbs_types_block_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("required")), node->required);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("self_type")), node->self_type);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Block,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->required);
            rb_gc_unregister_address(&node->self_type);

            free(instance);

            return obj;
        }
        case RBS_TYPES_CLASS_INSTANCE: {
            rbs_types_class_instance_t *node = (rbs_types_class_instance_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("args")), node->args);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_ClassInstance,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->args);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_CLASS_SINGLETON: {
            rbs_types_class_singleton_t *node = (rbs_types_class_singleton_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_ClassSingleton,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_FUNCTION: {
            rbs_types_function_t *node = (rbs_types_function_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("required_positionals")), node->required_positionals);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("optional_positionals")), node->optional_positionals);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("rest_positionals")), node->rest_positionals);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("trailing_positionals")), node->trailing_positionals);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("required_keywords")), node->required_keywords);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("optional_keywords")), node->optional_keywords);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("rest_keywords")), node->rest_keywords);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("return_type")), node->return_type);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Function,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->required_positionals);
            rb_gc_unregister_address(&node->optional_positionals);
            rb_gc_unregister_address(&node->rest_positionals);
            rb_gc_unregister_address(&node->trailing_positionals);
            rb_gc_unregister_address(&node->required_keywords);
            rb_gc_unregister_address(&node->optional_keywords);
            rb_gc_unregister_address(&node->rest_keywords);
            rb_gc_unregister_address(&node->return_type);

            free(instance);

            return obj;
        }
        case RBS_TYPES_FUNCTION_PARAM: {
            rbs_types_function_param_t *node = (rbs_types_function_param_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Function_Param,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_INTERFACE: {
            rbs_types_interface_t *node = (rbs_types_interface_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("args")), node->args);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Interface,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->args);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_INTERSECTION: {
            rbs_types_intersection_t *node = (rbs_types_intersection_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("types")), node->types);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Intersection,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->types);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_LITERAL: {
            rbs_types_literal_t *node = (rbs_types_literal_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("literal")), node->literal);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Literal,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->literal);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_OPTIONAL: {
            rbs_types_optional_t *node = (rbs_types_optional_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Optional,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_PROC: {
            rbs_types_proc_t *node = (rbs_types_proc_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("type")), node->type);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("block")), node->block);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("self_type")), node->self_type);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Proc,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->type);
            rb_gc_unregister_address(&node->block);
            rb_gc_unregister_address(&node->location);
            rb_gc_unregister_address(&node->self_type);

            free(instance);

            return obj;
        }
        case RBS_TYPES_RECORD: {
            rbs_types_record_t *node = (rbs_types_record_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("all_fields")), node->all_fields);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Record,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->all_fields);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_TUPLE: {
            rbs_types_tuple_t *node = (rbs_types_tuple_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("types")), node->types);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Tuple,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->types);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_UNION: {
            rbs_types_union_t *node = (rbs_types_union_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("types")), node->types);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Union,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->types);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_TYPES_UNTYPED_FUNCTION: {
            rbs_types_untyped_function_t *node = (rbs_types_untyped_function_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("return_type")), node->return_type);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_UntypedFunction,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->return_type);

            free(instance);

            return obj;
        }
        case RBS_TYPES_VARIABLE: {
            rbs_types_variable_t *node = (rbs_types_variable_t *)instance;

            VALUE _init_kwargs = rb_hash_new();
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("name")), node->name);
            rb_hash_aset(_init_kwargs, ID2SYM(rb_intern("location")), node->location);

            VALUE obj = CLASS_NEW_INSTANCE(
                RBS_Types_Variable,
                1,
                &_init_kwargs
            );

            // TODO: remove this once we do not use inner Ruby objects in our nodes.
            // Unmark the fields we previously marked as live during the node C struct creation (see `ast.c.erb`).
            // Now that we have created the Ruby object to hold the inner VALUE objects the GC won't collect them until
            // the Ruby instance is collected.
            rb_gc_unregister_address(&node->name);
            rb_gc_unregister_address(&node->location);

            free(instance);

            return obj;
        }
        case RBS_NODE_INSTANCE_WRAPPER: {
            return ((rbs_node_instance_wrapper_t *)instance)->instance;
        }
    }

    fprintf(stderr, "Unknown node type: %d\n", instance->type);
    exit(1);
}
