/*----------------------------------------------------------------------------*/
/* This file is generated by the templates/template.rb script and should not  */
/* be modified manually.                                                      */
/* To change the template see                                                 */
/* templates/ext/rbs_extension/ast_translation.h.erb                          */
/*----------------------------------------------------------------------------*/

#ifndef RBS_EXTENSION_AST_TRANSLATION_H
#define RBS_EXTENSION_AST_TRANSLATION_H

#include "rbs/ast.h"
#include "location.h"
#include "parserstate.h"

VALUE rbs_node_list_to_ruby_array(parserstate *parser, rbs_node_list_t *list);
VALUE rbs_hash_to_ruby_hash(parserstate *parser, rbs_hash_t *hash);
VALUE rbs_loc_to_ruby_location(parserstate *parser, rbs_location_t *loc);
VALUE rbs_struct_to_ruby_value(parserstate *parser, rbs_node_t *instance);

#endif
