/*----------------------------------------------------------------------------*/
/* This file is generated by the templates/template.rb script and should not  */
/* be modified manually.                                                      */
/* To change the template see                                                 */
/* templates/src/ast.c.erb                                                    */
/*----------------------------------------------------------------------------*/

#include "rbs/ast.h"

#include <stdlib.h>
#include "rbs/ruby_objs.h"

rbs_node_list_t* rbs_node_list_new(rbs_allocator_t *allocator) {
    rbs_node_list_t *list = rbs_allocator_alloc(allocator, rbs_node_list_t);
    *list = (rbs_node_list_t) {
        .allocator = allocator,
        .head = NULL,
        .tail = NULL,
        .length = 0,
        .cached_ruby_value = rb_ary_new(),
    };

    rb_gc_register_mark_object(list->cached_ruby_value);

    return list;
}

void rbs_node_list_append(rbs_node_list_t *list, rbs_node_t *node) {
    rb_gc_register_mark_object(node->cached_ruby_value);

    rbs_node_list_node_t *new_node = rbs_allocator_alloc(list->allocator, rbs_node_list_node_t);
    *new_node = (rbs_node_list_node_t) {
        .node = node,
        .next = NULL,
    };

    if (list->tail == NULL) {
        list->head = new_node;
        list->tail = new_node;
    } else {
        list->tail->next = new_node;
        list->tail = new_node;
    }
    list->length++;

    rb_ary_push(list->cached_ruby_value, node->cached_ruby_value);
}

rbs_ast_annotation_t *rbs_ast_annotation_new(rbs_allocator_t *allocator, VALUE string, rbs_location_t *location) {
    rbs_ast_annotation_t *instance = rbs_allocator_alloc(allocator, rbs_ast_annotation_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(string);
    rb_gc_register_mark_object(location->cached_ruby_value);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_annotation(string, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_annotation_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_ANNOTATION
        },
        .string = string,
        .location = location,
    };

    return instance;
}

rbs_ast_comment_t *rbs_ast_comment_new(rbs_allocator_t *allocator, VALUE ruby_value, VALUE string, rbs_location_t *location) {
    rbs_ast_comment_t *instance = rbs_allocator_alloc(allocator, rbs_ast_comment_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(string);
    rb_gc_register_mark_object(location->cached_ruby_value);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_comment_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_COMMENT
        },
        .string = string,
        .location = location,
    };

    return instance;
}

rbs_ast_declarations_class_t *rbs_ast_declarations_class_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_list_t *type_params, VALUE super_class, rbs_node_list_t *members, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment) {
    rbs_ast_declarations_class_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_class_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type_params->cached_ruby_value);
    rb_gc_register_mark_object(super_class);
    rb_gc_register_mark_object(members->cached_ruby_value);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_class(name, type_params, super_class, members, annotations, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_class_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_CLASS
        },
        .name = name,
        .type_params = type_params,
        .super_class = super_class,
        .members = members,
        .annotations = annotations,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_declarations_class_super_t *rbs_ast_declarations_class_super_new(rbs_allocator_t *allocator, VALUE name, rbs_node_list_t *args, rbs_location_t *location) {
    rbs_ast_declarations_class_super_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_class_super_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name);
    rb_gc_register_mark_object(args->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_class_super(name, args, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_class_super_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_CLASS_SUPER
        },
        .name = name,
        .args = args,
        .location = location,
    };

    return instance;
}

rbs_ast_declarations_classalias_t *rbs_ast_declarations_classalias_new(rbs_allocator_t *allocator, rbs_typename_t *new_name, rbs_typename_t *old_name, rbs_location_t *location, VALUE comment) {
    rbs_ast_declarations_classalias_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_classalias_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(new_name->base.cached_ruby_value);
    rb_gc_register_mark_object(old_name->base.cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_class_alias(new_name, old_name, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_classalias_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_CLASSALIAS
        },
        .new_name = new_name,
        .old_name = old_name,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_declarations_constant_t *rbs_ast_declarations_constant_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_t *type, rbs_location_t *location, VALUE comment) {
    rbs_ast_declarations_constant_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_constant_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_constant(name, type, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_constant_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_CONSTANT
        },
        .name = name,
        .type = type,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_declarations_global_t *rbs_ast_declarations_global_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_node_t *type, rbs_location_t *location, VALUE comment) {
    rbs_ast_declarations_global_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_global_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_global(name, type, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_global_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_GLOBAL
        },
        .name = name,
        .type = type,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_declarations_interface_t *rbs_ast_declarations_interface_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_list_t *type_params, rbs_node_list_t *members, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment) {
    rbs_ast_declarations_interface_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_interface_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type_params->cached_ruby_value);
    rb_gc_register_mark_object(members->cached_ruby_value);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_interface(name, type_params, members, annotations, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_interface_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_INTERFACE
        },
        .name = name,
        .type_params = type_params,
        .members = members,
        .annotations = annotations,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_declarations_module_t *rbs_ast_declarations_module_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_list_t *type_params, rbs_node_list_t *self_types, rbs_node_list_t *members, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment) {
    rbs_ast_declarations_module_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_module_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type_params->cached_ruby_value);
    rb_gc_register_mark_object(self_types->cached_ruby_value);
    rb_gc_register_mark_object(members->cached_ruby_value);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_module(name, type_params, self_types, members, annotations, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_module_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_MODULE
        },
        .name = name,
        .type_params = type_params,
        .self_types = self_types,
        .members = members,
        .annotations = annotations,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_declarations_module_self_t *rbs_ast_declarations_module_self_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_list_t *args, rbs_location_t *location) {
    rbs_ast_declarations_module_self_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_module_self_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(args->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_module_self(name, args, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_module_self_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_MODULE_SELF
        },
        .name = name,
        .args = args,
        .location = location,
    };

    return instance;
}

rbs_ast_declarations_modulealias_t *rbs_ast_declarations_modulealias_new(rbs_allocator_t *allocator, rbs_typename_t *new_name, rbs_typename_t *old_name, rbs_location_t *location, VALUE comment) {
    rbs_ast_declarations_modulealias_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_modulealias_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(new_name->base.cached_ruby_value);
    rb_gc_register_mark_object(old_name->base.cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_module_alias(new_name, old_name, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_modulealias_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_MODULEALIAS
        },
        .new_name = new_name,
        .old_name = old_name,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_declarations_nodes_t *rbs_ast_declarations_nodes_new(rbs_allocator_t *allocator, VALUE ruby_value, rbs_node_list_t *declarations) {
    rbs_ast_declarations_nodes_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_nodes_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(declarations->cached_ruby_value);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_nodes_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_NODES
        },
        .declarations = declarations,
    };

    return instance;
}

rbs_ast_declarations_typealias_t *rbs_ast_declarations_typealias_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_list_t *type_params, rbs_node_t *type, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment) {
    rbs_ast_declarations_typealias_t *instance = rbs_allocator_alloc(allocator, rbs_ast_declarations_typealias_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type_params->cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_decl_type_alias(name, type_params, type, annotations, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_declarations_typealias_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DECLARATIONS_TYPEALIAS
        },
        .name = name,
        .type_params = type_params,
        .type = type,
        .annotations = annotations,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_directives_nodes_t *rbs_ast_directives_nodes_new(rbs_allocator_t *allocator, VALUE ruby_value, rbs_node_list_t *directives) {
    rbs_ast_directives_nodes_t *instance = rbs_allocator_alloc(allocator, rbs_ast_directives_nodes_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(directives->cached_ruby_value);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_directives_nodes_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DIRECTIVES_NODES
        },
        .directives = directives,
    };

    return instance;
}

rbs_ast_directives_use_t *rbs_ast_directives_use_new(rbs_allocator_t *allocator, rbs_node_list_t *clauses, rbs_location_t *location) {
    rbs_ast_directives_use_t *instance = rbs_allocator_alloc(allocator, rbs_ast_directives_use_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(clauses->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_directives_use(clauses, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_directives_use_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DIRECTIVES_USE
        },
        .clauses = clauses,
        .location = location,
    };

    return instance;
}

rbs_ast_directives_use_singleclause_t *rbs_ast_directives_use_singleclause_new(rbs_allocator_t *allocator, VALUE ruby_value, VALUE type_name, VALUE new_name, rbs_location_t *location) {
    rbs_ast_directives_use_singleclause_t *instance = rbs_allocator_alloc(allocator, rbs_ast_directives_use_singleclause_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(type_name);
    rb_gc_register_mark_object(new_name);
    rb_gc_register_mark_object(location->cached_ruby_value);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_directives_use_singleclause_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DIRECTIVES_USE_SINGLECLAUSE
        },
        .type_name = type_name,
        .new_name = new_name,
        .location = location,
    };

    return instance;
}

rbs_ast_directives_use_wildcardclause_t *rbs_ast_directives_use_wildcardclause_new(rbs_allocator_t *allocator, VALUE ruby_value, rbs_namespace_t *namespace, rbs_location_t *location) {
    rbs_ast_directives_use_wildcardclause_t *instance = rbs_allocator_alloc(allocator, rbs_ast_directives_use_wildcardclause_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(namespace->base.cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_directives_use_wildcardclause_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_DIRECTIVES_USE_WILDCARDCLAUSE
        },
        .namespace = namespace,
        .location = location,
    };

    return instance;
}

rbs_ast_members_alias_t *rbs_ast_members_alias_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *new_name, rbs_ast_symbol_t *old_name, rbs_ast_symbol_t *kind, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment) {
    rbs_ast_members_alias_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_alias_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(new_name->base.cached_ruby_value);
    rb_gc_register_mark_object(old_name->base.cached_ruby_value);
    rb_gc_register_mark_object(kind->base.cached_ruby_value);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_alias(new_name, old_name, kind, annotations, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_alias_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_ALIAS
        },
        .new_name = new_name,
        .old_name = old_name,
        .kind = kind,
        .annotations = annotations,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_members_attraccessor_t *rbs_ast_members_attraccessor_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_node_t *type, VALUE ivar_name, VALUE kind, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment, VALUE visibility) {
    rbs_ast_members_attraccessor_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_attraccessor_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(ivar_name);
    rb_gc_register_mark_object(kind);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);
    rb_gc_register_mark_object(visibility);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_attr_accessor(name, type, ivar_name, kind, annotations, location, comment, visibility);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_attraccessor_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_ATTRACCESSOR
        },
        .name = name,
        .type = type,
        .ivar_name = ivar_name,
        .kind = kind,
        .annotations = annotations,
        .location = location,
        .comment = comment,
        .visibility = visibility,
    };

    return instance;
}

rbs_ast_members_attrreader_t *rbs_ast_members_attrreader_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_node_t *type, VALUE ivar_name, VALUE kind, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment, VALUE visibility) {
    rbs_ast_members_attrreader_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_attrreader_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(ivar_name);
    rb_gc_register_mark_object(kind);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);
    rb_gc_register_mark_object(visibility);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_attr_reader(name, type, ivar_name, kind, annotations, location, comment, visibility);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_attrreader_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_ATTRREADER
        },
        .name = name,
        .type = type,
        .ivar_name = ivar_name,
        .kind = kind,
        .annotations = annotations,
        .location = location,
        .comment = comment,
        .visibility = visibility,
    };

    return instance;
}

rbs_ast_members_attrwriter_t *rbs_ast_members_attrwriter_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_node_t *type, VALUE ivar_name, VALUE kind, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment, VALUE visibility) {
    rbs_ast_members_attrwriter_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_attrwriter_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(ivar_name);
    rb_gc_register_mark_object(kind);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);
    rb_gc_register_mark_object(visibility);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_attr_writer(name, type, ivar_name, kind, annotations, location, comment, visibility);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_attrwriter_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_ATTRWRITER
        },
        .name = name,
        .type = type,
        .ivar_name = ivar_name,
        .kind = kind,
        .annotations = annotations,
        .location = location,
        .comment = comment,
        .visibility = visibility,
    };

    return instance;
}

rbs_ast_members_classinstancevariable_t *rbs_ast_members_classinstancevariable_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_node_t *type, rbs_location_t *location, VALUE comment) {
    rbs_ast_members_classinstancevariable_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_classinstancevariable_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_class_instance_variable(name, type, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_classinstancevariable_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_CLASSINSTANCEVARIABLE
        },
        .name = name,
        .type = type,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_members_classvariable_t *rbs_ast_members_classvariable_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_node_t *type, rbs_location_t *location, VALUE comment) {
    rbs_ast_members_classvariable_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_classvariable_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_class_variable(name, type, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_classvariable_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_CLASSVARIABLE
        },
        .name = name,
        .type = type,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_members_extend_t *rbs_ast_members_extend_new(rbs_allocator_t *allocator, VALUE name, rbs_node_list_t *args, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment) {
    rbs_ast_members_extend_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_extend_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name);
    rb_gc_register_mark_object(args->cached_ruby_value);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_extend(name, args, annotations, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_extend_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_EXTEND
        },
        .name = name,
        .args = args,
        .annotations = annotations,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_members_include_t *rbs_ast_members_include_new(rbs_allocator_t *allocator, VALUE name, rbs_node_list_t *args, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment) {
    rbs_ast_members_include_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_include_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name);
    rb_gc_register_mark_object(args->cached_ruby_value);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_include(name, args, annotations, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_include_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_INCLUDE
        },
        .name = name,
        .args = args,
        .annotations = annotations,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_members_instancevariable_t *rbs_ast_members_instancevariable_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_node_t *type, rbs_location_t *location, VALUE comment) {
    rbs_ast_members_instancevariable_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_instancevariable_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_instance_variable(name, type, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_instancevariable_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_INSTANCEVARIABLE
        },
        .name = name,
        .type = type,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_members_methoddefinition_t *rbs_ast_members_methoddefinition_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_ast_symbol_t *kind, VALUE overloads, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment, VALUE overloading, VALUE visibility) {
    rbs_ast_members_methoddefinition_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_methoddefinition_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(kind->base.cached_ruby_value);
    rb_gc_register_mark_object(overloads);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);
    rb_gc_register_mark_object(overloading);
    rb_gc_register_mark_object(visibility);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_method_definition(name, kind, overloads, annotations, location, comment, overloading, visibility);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_methoddefinition_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_METHODDEFINITION
        },
        .name = name,
        .kind = kind,
        .overloads = overloads,
        .annotations = annotations,
        .location = location,
        .comment = comment,
        .overloading = overloading,
        .visibility = visibility,
    };

    return instance;
}

rbs_ast_members_methoddefinition_overload_t *rbs_ast_members_methoddefinition_overload_new(rbs_allocator_t *allocator, VALUE ruby_value, VALUE annotations, VALUE method_type) {
    rbs_ast_members_methoddefinition_overload_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_methoddefinition_overload_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(annotations);
    rb_gc_register_mark_object(method_type);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_methoddefinition_overload_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_METHODDEFINITION_OVERLOAD
        },
        .annotations = annotations,
        .method_type = method_type,
    };

    return instance;
}

rbs_ast_members_prepend_t *rbs_ast_members_prepend_new(rbs_allocator_t *allocator, VALUE name, rbs_node_list_t *args, rbs_node_list_t *annotations, rbs_location_t *location, VALUE comment) {
    rbs_ast_members_prepend_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_prepend_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name);
    rb_gc_register_mark_object(args->cached_ruby_value);
    rb_gc_register_mark_object(annotations->cached_ruby_value);
    rb_gc_register_mark_object(location->cached_ruby_value);
    rb_gc_register_mark_object(comment);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_prepend(name, args, annotations, location, comment);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_prepend_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_PREPEND
        },
        .name = name,
        .args = args,
        .annotations = annotations,
        .location = location,
        .comment = comment,
    };

    return instance;
}

rbs_ast_members_private_t *rbs_ast_members_private_new(rbs_allocator_t *allocator, rbs_location_t *location) {
    rbs_ast_members_private_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_private_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location->cached_ruby_value);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_private(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_private_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_PRIVATE
        },
        .location = location,
    };

    return instance;
}

rbs_ast_members_public_t *rbs_ast_members_public_new(rbs_allocator_t *allocator, rbs_location_t *location) {
    rbs_ast_members_public_t *instance = rbs_allocator_alloc(allocator, rbs_ast_members_public_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location->cached_ruby_value);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_members_public(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_members_public_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_MEMBERS_PUBLIC
        },
        .location = location,
    };

    return instance;
}

rbs_ast_symbol_t *rbs_ast_symbol_new(rbs_allocator_t *allocator, VALUE ruby_value) {
    rbs_ast_symbol_t *instance = rbs_allocator_alloc(allocator, rbs_ast_symbol_t);

    // Disable GC for all these Ruby objects.


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_symbol_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_SYMBOL
        },
    };

    return instance;
}

rbs_ast_typeparam_t *rbs_ast_typeparam_new(rbs_allocator_t *allocator, rbs_ast_symbol_t *name, rbs_ast_symbol_t *variance, VALUE upper_bound, VALUE default_type, VALUE unchecked, rbs_location_t *location) {
    rbs_ast_typeparam_t *instance = rbs_allocator_alloc(allocator, rbs_ast_typeparam_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(variance->base.cached_ruby_value);
    rb_gc_register_mark_object(upper_bound);
    rb_gc_register_mark_object(default_type);
    rb_gc_register_mark_object(unchecked);
    rb_gc_register_mark_object(location->cached_ruby_value);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_ast_type_param(name, variance, upper_bound, default_type, unchecked, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_ast_typeparam_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_AST_TYPEPARAM
        },
        .name = name,
        .variance = variance,
        .upper_bound = upper_bound,
        .default_type = default_type,
        .unchecked = unchecked,
        .location = location,
    };

    return instance;
}

rbs_methodtype_t *rbs_methodtype_new(rbs_allocator_t *allocator, rbs_node_list_t *type_params, VALUE type, VALUE block, VALUE location) {
    rbs_methodtype_t *instance = rbs_allocator_alloc(allocator, rbs_methodtype_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(type_params->cached_ruby_value);
    rb_gc_register_mark_object(type);
    rb_gc_register_mark_object(block);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_method_type(type_params, type, block, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_methodtype_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_METHODTYPE
        },
        .type_params = type_params,
        .type = type,
        .block = block,
        .location = location,
    };

    return instance;
}

rbs_namespace_t *rbs_namespace_new(rbs_allocator_t *allocator, rbs_node_list_t *path, VALUE absolute) {
    rbs_namespace_t *instance = rbs_allocator_alloc(allocator, rbs_namespace_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(path->cached_ruby_value);
    rb_gc_register_mark_object(absolute);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_namespace(path, absolute);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_namespace_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_NAMESPACE
        },
        .path = path,
        .absolute = absolute,
    };

    return instance;
}

rbs_typename_t *rbs_typename_new(rbs_allocator_t *allocator, VALUE namespace, VALUE name) {
    rbs_typename_t *instance = rbs_allocator_alloc(allocator, rbs_typename_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(namespace);
    rb_gc_register_mark_object(name);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_type_name(namespace, name);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_typename_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPENAME
        },
        .namespace = namespace,
        .name = name,
    };

    return instance;
}

rbs_types_alias_t *rbs_types_alias_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_list_t *args, VALUE location) {
    rbs_types_alias_t *instance = rbs_allocator_alloc(allocator, rbs_types_alias_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(args->cached_ruby_value);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_alias(name, args, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_alias_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_ALIAS
        },
        .name = name,
        .args = args,
        .location = location,
    };

    return instance;
}

rbs_types_bases_any_t *rbs_types_bases_any_new(rbs_allocator_t *allocator, VALUE todo, VALUE location) {
    rbs_types_bases_any_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_any_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(todo);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_any(todo, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_any_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_ANY
        },
        .todo = todo,
        .location = location,
    };

    return instance;
}

rbs_types_bases_bool_t *rbs_types_bases_bool_new(rbs_allocator_t *allocator, VALUE location) {
    rbs_types_bases_bool_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_bool_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_bool(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_bool_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_BOOL
        },
        .location = location,
    };

    return instance;
}

rbs_types_bases_bottom_t *rbs_types_bases_bottom_new(rbs_allocator_t *allocator, VALUE location) {
    rbs_types_bases_bottom_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_bottom_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_bottom(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_bottom_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_BOTTOM
        },
        .location = location,
    };

    return instance;
}

rbs_types_bases_class_t *rbs_types_bases_class_new(rbs_allocator_t *allocator, VALUE location) {
    rbs_types_bases_class_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_class_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_class(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_class_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_CLASS
        },
        .location = location,
    };

    return instance;
}

rbs_types_bases_instance_t *rbs_types_bases_instance_new(rbs_allocator_t *allocator, VALUE location) {
    rbs_types_bases_instance_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_instance_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_instance(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_instance_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_INSTANCE
        },
        .location = location,
    };

    return instance;
}

rbs_types_bases_nil_t *rbs_types_bases_nil_new(rbs_allocator_t *allocator, VALUE location) {
    rbs_types_bases_nil_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_nil_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_nil(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_nil_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_NIL
        },
        .location = location,
    };

    return instance;
}

rbs_types_bases_self_t *rbs_types_bases_self_new(rbs_allocator_t *allocator, VALUE location) {
    rbs_types_bases_self_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_self_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_self(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_self_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_SELF
        },
        .location = location,
    };

    return instance;
}

rbs_types_bases_top_t *rbs_types_bases_top_new(rbs_allocator_t *allocator, VALUE location) {
    rbs_types_bases_top_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_top_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_top(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_top_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_TOP
        },
        .location = location,
    };

    return instance;
}

rbs_types_bases_void_t *rbs_types_bases_void_new(rbs_allocator_t *allocator, VALUE location) {
    rbs_types_bases_void_t *instance = rbs_allocator_alloc(allocator, rbs_types_bases_void_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_bases_void(location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_bases_void_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BASES_VOID
        },
        .location = location,
    };

    return instance;
}

rbs_types_block_t *rbs_types_block_new(rbs_allocator_t *allocator, VALUE ruby_value, VALUE type, VALUE required, VALUE self_type) {
    rbs_types_block_t *instance = rbs_allocator_alloc(allocator, rbs_types_block_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(type);
    rb_gc_register_mark_object(required);
    rb_gc_register_mark_object(self_type);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_block_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_BLOCK
        },
        .type = type,
        .required = required,
        .self_type = self_type,
    };

    return instance;
}

rbs_types_classinstance_t *rbs_types_classinstance_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_list_t *args, VALUE location) {
    rbs_types_classinstance_t *instance = rbs_allocator_alloc(allocator, rbs_types_classinstance_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(args->cached_ruby_value);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_class_instance(name, args, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_classinstance_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_CLASSINSTANCE
        },
        .name = name,
        .args = args,
        .location = location,
    };

    return instance;
}

rbs_types_classsingleton_t *rbs_types_classsingleton_new(rbs_allocator_t *allocator, rbs_typename_t *name, VALUE location) {
    rbs_types_classsingleton_t *instance = rbs_allocator_alloc(allocator, rbs_types_classsingleton_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_class_singleton(name, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_classsingleton_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_CLASSSINGLETON
        },
        .name = name,
        .location = location,
    };

    return instance;
}

rbs_types_function_t *rbs_types_function_new(rbs_allocator_t *allocator, VALUE ruby_value, VALUE required_positionals, VALUE optional_positionals, VALUE rest_positionals, VALUE trailing_positionals, VALUE required_keywords, VALUE optional_keywords, VALUE rest_keywords, VALUE return_type) {
    rbs_types_function_t *instance = rbs_allocator_alloc(allocator, rbs_types_function_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(required_positionals);
    rb_gc_register_mark_object(optional_positionals);
    rb_gc_register_mark_object(rest_positionals);
    rb_gc_register_mark_object(trailing_positionals);
    rb_gc_register_mark_object(required_keywords);
    rb_gc_register_mark_object(optional_keywords);
    rb_gc_register_mark_object(rest_keywords);
    rb_gc_register_mark_object(return_type);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_function_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_FUNCTION
        },
        .required_positionals = required_positionals,
        .optional_positionals = optional_positionals,
        .rest_positionals = rest_positionals,
        .trailing_positionals = trailing_positionals,
        .required_keywords = required_keywords,
        .optional_keywords = optional_keywords,
        .rest_keywords = rest_keywords,
        .return_type = return_type,
    };

    return instance;
}

rbs_types_function_param_t *rbs_types_function_param_new(rbs_allocator_t *allocator, rbs_node_t *type, VALUE name, rbs_location_t *location) {
    rbs_types_function_param_t *instance = rbs_allocator_alloc(allocator, rbs_types_function_param_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(name);
    rb_gc_register_mark_object(location->cached_ruby_value);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_function_param(type, name, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_function_param_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_FUNCTION_PARAM
        },
        .type = type,
        .name = name,
        .location = location,
    };

    return instance;
}

rbs_types_interface_t *rbs_types_interface_new(rbs_allocator_t *allocator, rbs_typename_t *name, rbs_node_list_t *args, VALUE location) {
    rbs_types_interface_t *instance = rbs_allocator_alloc(allocator, rbs_types_interface_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name->base.cached_ruby_value);
    rb_gc_register_mark_object(args->cached_ruby_value);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_interface(name, args, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_interface_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_INTERFACE
        },
        .name = name,
        .args = args,
        .location = location,
    };

    return instance;
}

rbs_types_intersection_t *rbs_types_intersection_new(rbs_allocator_t *allocator, rbs_node_list_t *types, VALUE location) {
    rbs_types_intersection_t *instance = rbs_allocator_alloc(allocator, rbs_types_intersection_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(types->cached_ruby_value);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_intersection(types, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_intersection_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_INTERSECTION
        },
        .types = types,
        .location = location,
    };

    return instance;
}

rbs_types_literal_t *rbs_types_literal_new(rbs_allocator_t *allocator, VALUE literal, VALUE location) {
    rbs_types_literal_t *instance = rbs_allocator_alloc(allocator, rbs_types_literal_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(literal);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_literal(literal, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_literal_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_LITERAL
        },
        .literal = literal,
        .location = location,
    };

    return instance;
}

rbs_types_optional_t *rbs_types_optional_new(rbs_allocator_t *allocator, rbs_node_t *type, VALUE location) {
    rbs_types_optional_t *instance = rbs_allocator_alloc(allocator, rbs_types_optional_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(type->cached_ruby_value);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_optional(type, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_optional_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_OPTIONAL
        },
        .type = type,
        .location = location,
    };

    return instance;
}

rbs_types_proc_t *rbs_types_proc_new(rbs_allocator_t *allocator, VALUE type, VALUE block, VALUE location, VALUE self_type) {
    rbs_types_proc_t *instance = rbs_allocator_alloc(allocator, rbs_types_proc_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(type);
    rb_gc_register_mark_object(block);
    rb_gc_register_mark_object(location);
    rb_gc_register_mark_object(self_type);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_proc(type, block, location, self_type);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_proc_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_PROC
        },
        .type = type,
        .block = block,
        .location = location,
        .self_type = self_type,
    };

    return instance;
}

rbs_types_record_t *rbs_types_record_new(rbs_allocator_t *allocator, VALUE all_fields, VALUE location) {
    rbs_types_record_t *instance = rbs_allocator_alloc(allocator, rbs_types_record_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(all_fields);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_record(all_fields, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_record_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_RECORD
        },
        .all_fields = all_fields,
        .location = location,
    };

    return instance;
}

rbs_types_tuple_t *rbs_types_tuple_new(rbs_allocator_t *allocator, rbs_node_list_t *types, VALUE location) {
    rbs_types_tuple_t *instance = rbs_allocator_alloc(allocator, rbs_types_tuple_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(types->cached_ruby_value);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_tuple(types, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_tuple_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_TUPLE
        },
        .types = types,
        .location = location,
    };

    return instance;
}

rbs_types_union_t *rbs_types_union_new(rbs_allocator_t *allocator, rbs_node_list_t *types, VALUE location) {
    rbs_types_union_t *instance = rbs_allocator_alloc(allocator, rbs_types_union_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(types->cached_ruby_value);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_union(types, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_union_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_UNION
        },
        .types = types,
        .location = location,
    };

    return instance;
}

rbs_types_untypedfunction_t *rbs_types_untypedfunction_new(rbs_allocator_t *allocator, VALUE ruby_value, VALUE return_type) {
    rbs_types_untypedfunction_t *instance = rbs_allocator_alloc(allocator, rbs_types_untypedfunction_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(return_type);


    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_untypedfunction_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_UNTYPEDFUNCTION
        },
        .return_type = return_type,
    };

    return instance;
}

rbs_types_variable_t *rbs_types_variable_new(rbs_allocator_t *allocator, VALUE name, VALUE location) {
    rbs_types_variable_t *instance = rbs_allocator_alloc(allocator, rbs_types_variable_t);

    // Disable GC for all these Ruby objects.
    rb_gc_register_mark_object(name);
    rb_gc_register_mark_object(location);

    // Generate our own Ruby VALUE here, rather than accepting it from a parameter.
    VALUE ruby_value = rbs_variable(name, location);

    rb_gc_register_mark_object(ruby_value);

    *instance = (rbs_types_variable_t) {
        .base = (rbs_node_t) {
            .cached_ruby_value = ruby_value,
            .type = RBS_TYPES_VARIABLE
        },
        .name = name,
        .location = location,
    };

    return instance;
}

