name: Rust

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/rust.yml"
      - "rust/**"
      - "include/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/rust.yml"
      - "rust/**"
      - "include/**"
      - "src/**"

env:
  RUSTFLAGS: "-D warnings"

jobs:
  test:
    name: cargo:test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust tools
        run: |
          rustup update --no-self-update stable
          rustup default stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run tests
        run: |
          cd rust
          cargo test --verbose

  lint:
    name: cargo:lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust tools
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add --toolchain stable clippy rustfmt
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Check formatting
        run: |
          cd rust
          cargo fmt --check
      - name: Run clippy
        run: |
          cd rust
          cargo clippy
